VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "cIDispatch"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Function GetIDsOfNames(riid As IID, rgszNames As LPOLESTRArrayPtr, cNames As UINT, LCID As LCID, rgDispId As DISPIDArrayPtr) As Long

End Function

Function GetTypeInfo(iTInfo As UINT, LCID As LCID, ppTInfo As ITypeInfoPtr) As Long

End Function

Function GetTypeInfoCount(pctinfo As UINT) As Long

End Function

Function Invoke(dispIdMember As DISPID, riid As IID, LCID As LCID, wFlags As WORD, pDispParams As VBDISPPARAMS, pVarResult As VARIANTPtr, pExcepInfo As VBEXCEPINFO, puArgErr As UINT) As Long

End Function

